### ISSUE TITLE
Incorrect minimum Python version

### ISSUE THREAD

**Issue by DManowitz** [conda-forge/faker-feedstock#242]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

This conda-forge package indicates `python >=3.7` as its Python dependency.  However, as seen in the [Github repo](https://github.com/joke2k/faker/blob/v19.0.0/setup.py), the upstream project has required `python >=3.8` since faker v19.0.0.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by ocefpaf** [comment]
Thanks for fixing this.
